### PR TITLE
Changed the JQuery detection

### PR DESCRIPTION
**Pull request by priandsf**
In our application, we need to force Angular to use jqLite while jQuery is loaded. The current detection mechanism is checking if jQuery is loaded, but not if it is actually used.
This pull request is checking if `Angular.element` is effectively jQuery by checking if `angular.element.fn.jquery` is defined, meaning that jQuery is the library used by Angular.

### CODE REVIEW

**Comment by priandsf** [comment]
@dhilt Hello Denis - Are you willing to merge these pull requests or do you have any concern with them?

**Comment by dhilt** [comment]
@priandsf Sorry, I haven't been here for 1 week...
 - I don't see code related to jQuery, probably you didn't commit it
 - $digest things would be better to keep in PR https://github.com/angular-ui/ui-scroll/pull/221

**Comment by priandsf** [comment]
@dhilt Not a prblem - I'll be out soon as well :-)
The Jquery detection is pushed as PR#222 (https://github.com/angular-ui/ui-scroll/pull/222/commits/55f627cce1afb9e54613b65769b8ecdff4a8fa13), from this branch: https://github.com/priandsf/ui-scroll/tree/jquery-detection
The $digest fixes are only in PR#221

**Comment by dhilt** [comment]
@priandsf I [cherry-picked your commit](https://github.com/angular-ui/ui-scroll/commit/43561dd645174d4315f5c84be96daf1393205c90) and released angular-ui-scroll v1.7.4 with only jqLite/jQuery stuff. Could you please check if it does work for you? And let's continue optimization things in https://github.com/angular-ui/ui-scroll/pull/221.

**Comment by priandsf** [comment]
Thanks @dhilt I tested it and it works!

**Pull request closed without merging**
