### PR TITLE
Remove ES6 code to fix old browser compatibility

### PR DESCRIPTION
**Pull request by evanlok**
`Number.isInteger` is not supported on older browsers. babel polyfill fixes compatibility.

https://caniuse.com/#feat=es6-number

### CODE REVIEW

**Comment by dhilt** [comment]
@evanlok Thanks a lot for the PR! 

I'm investigating the difference. The main bundle size is being increased from 58 to 96 Kb. Replacing `Number.isInteger` with a simplest polyfill I'm getting 95 Kb with `babel-plugin-transform-runtime` plugin enabled. So what are the others 37 Kb? Do we really need `babel-plugin-transform-runtime` if `Number.isInteger` is the only problem?

**Comment by evanlok** [comment]
@dhilt It looks like transform-runtime includes the entire polyfill and not just the ones used in the source code. I couldn't find any configuration that would change the behavior unfortunately. I've refactored this to implement `isInteger` function in a util module which should make the size increase negligible. I don't know if there is other ES6 code being used, but the changes I've made are working for me on IE11.

**Comment by dhilt** [comment]
@evanlok oh, Angular already has all necessary stuff for such a refactoring, may I ask you to replace following things in ./src folder?

 - isInteger (Number.isInteger) --> angular.isNumber
 - Array.isArray --> angular.isArray
 - Object.assign --> angular.extend

 I believe it should be enough to cover IE 9+ and then I will accept PR.

**Comment by dhilt** [comment]
@evanlok A good question. Let me think a bit, maybe I'll return your util method. I have to leave for some days, then I'll make a release. Accepting this PR, thanks!

**Pull request merged**
