### PR TITLE
properly detect digest in progress

### PR DESCRIPTION
**Pull request by zacronos**
I'm hitting the `$digest already in progress` error when using `applyUpdates` with 1.7.0-rc.2 -- this seems to fix the issue for me.  I'm not sure exactly how to reproduce the issue, but I can verify the fix at least for my project.

### CODE REVIEW

**Comment by zacronos** [comment]
This might fix #179.

**Comment by dhilt** [comment]
@zacronos This is why this feature is still in release candidate. It's new and in 1.6 it was just https://github.com/angular-ui/ui-scroll/blob/v1.6.2/src/ui-scroll.js#L336. This is really important part of the component's core and I felt that something's still not okey here. I believe you suggestion is very close to the finalize it. Before accepting this PR, I'd think about writing a test. So if could think about a repro, it will help!

**Comment by zacronos** [comment]
@dhilt a comment to [this SO answer](https://stackoverflow.com/a/12859093/751577) mentions the need for checking `$$phase` on both scope and root scope, and speculates that is has something to do with isolated scopes.  So perhaps if `ui-scroll` is within the template of a directive with isolated scope, that is when we can duplicate?

If I get the time, I'll try to reproduce with that approach -- however work has gotten very busy for me so we'll see.

**Comment by dhilt** [comment]
@zacronos Thanks! I'm going to merge it right now, but it needs to be further investigated.

In addition I would like to say that we already have something on that score, I mean the scroll event handler. And you don't see [there](https://github.com/angular-ui/ui-scroll/blob/v1.7.0-rc.2/src/ui-scroll.js#L437) a `!$rootScope.$$phase` protection due to it is present in the [beginning](https://github.com/angular-ui/ui-scroll/blob/v1.7.0-rc.2/src/ui-scroll.js#L429) of function.

**Comment by zacronos** [comment]
Yep, I did see that, which is why I didn't add the additional guard in that function.

FYI, I forgot to mention that the isolated scope directive scenario I described above is actually the case in my project, so there is supporting evidence that that is when it is necessary.

**Pull request merged**
